force-app/main/default/objects/Fundraising_Team__c/Fundraising_Team__c.object-meta.xml
<CustomObject>
    <label>Fundraising Team</label>
    <nameField>
        <label>Fundraising Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fundraising Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fundraising_Team__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fundraising Teams</relationshipLabel>
    <relationshipName>Fundraising_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fundraising_Team__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fundraising Teams</relationshipLabel>
    <relationshipName>Fundraising_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fundraising_Team__c/fields/Previous_Year_Donations__c.field-meta.xml
<CustomField>
    <fullName>Previous_Year_Donations__c</fullName>
    <label>Previous Year Donations</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fundraising_Team__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundraisingTeamBatch.cls
public with sharing class FundraisingTeamBatch implements Database.Batchable<SObject>,Database.Stateful{
    
    
    public Database.QueryLocator start(Database.BatchableContext ctx){
        return Database.getQueryLocator([SELECT Id,Contact__c,Organization__c,Start_Date__c,End_Date__c,Type__c,
                                         Previous_Year_Donations__c FROM Fundraising_Team__c]);
    }
    
    public void execute(Database.BatchableContext ctx, List<Fundraising_Team__c> records){
        Date todayDate = System.today();
        Date currentYearStart = date.newinstance(System.Today().year(), 1, 1);
        Date PreviousYearStart = date.newinstance(System.Today().year() - 1, 1, 1);
        List<Fundraising_Team__c> listtoUpdate = new List<Fundraising_Team__c>();
        
        for(Fundraising_Team__c obj : records){
            Decimal previousYearDonation = 0;
            if(obj.Type__c != 'Primary' || obj.Start_Date__c > todayDate || obj.End_Date__c < todayDate){
                obj.Previous_Year_Donations__c = 0;
            }else{
                for(Opportunity oppObj : [Select id,Amount,(Select id from OpportunityContactRoles where Role = 'Donor' OR Role = 'Soft Credit') from Opportunity where CloseDate < :currentYearStart AND CloseDate > :PreviousYearStart AND StageName = 'Closed Won' AND ((ContactId != null AND ContactId = :obj.Contact__c) OR (AccountId != null AND AccountId = :obj.Organization__c))]){
                    if(oppObj.Amount != null){
                        previousYearDonation = previousYearDonation + oppObj.Amount ;
                    }             
                }
                obj.Previous_Year_Donations__c = previousYearDonation;
            }
            listtoUpdate.add(obj);
        }
        Database.update(listtoUpdate, false);
    }
        
        public void finish(Database.BatchableContext ctx){
            
        }
    }